name = "james-email-service"
main = "worker/index.ts"
compatibility_date = "2026-08-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true

[triggers]
crons = ["* * * * *"]

[vars]
APP_DOMAIN = "jamesfontanilla.com"
SUPABASE_URL = "https://iketybhztvmujhgdmriu.supabase.co"

[[routes]]
pattern = "sulathq.jamesfontanilla.com"
custom_domain = true
